version: '2.3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
       - "0.0.0.0:8080:8080"
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY} 
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      AWS_REGION: ${AWS_REGION}
      AWS_ENDPOINT_URL: http://localstack:4566
      MONGO_URI: mongodb://root:example@mongo:27017
      SEARCH_SERVICE_HOST: http://search-service:5001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - mongo
      - redis
      - training-service
    env_file:
      - .env
    networks:
      - app-network

  search-service:
    build:
      context: ./trainer
      dockerfile: Dockerfile.python
    environment:
      # Unified cache configuration
      TRANSFORMERS_CACHE: /app/cache/transformers
      HF_HOME: /app/cache/huggingface
      TORCH_HOME: /app/cache/torch
      XDG_CACHE_HOME: /app/cache
      # Model storage
      MODEL_STORAGE_DIR: /app/models
      # AWS configuration
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      # GPU configuration
      NVIDIA_VISIBLE_DEVICES: all
      NLTK_DATA: /app/cache/nltk_data
    command: ["python", "search_service.py"]
    volumes:
      - ./cache:/app/cache:rw  # Add explicit read-write flag
      - ./models:/app/models:rw  # Add explicit read-write flag
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      - redis
      - ml-base

  ml-base:
    build:
      context: ./trainer
      dockerfile: Dockerfile.base
    image: ml-base:latest

  training-service:
    build:
      context: ./trainer
      dockerfile: Dockerfile.python
    environment:
      # Shared cache configuration
      TRANSFORMERS_CACHE: /app/cache/transformers
      HF_HOME: /app/cache/huggingface
      TORCH_HOME: /app/cache/torch
      # Model storage
      MODEL_STORAGE_DIR: /app/models
      # Training-specific settings
      TRAINING_QUEUE: training_queue
      MODEL_PREFIX: model_status
    ports:
      - "5000:5000"
    command: ["python", "training_service.py"]
    volumes:
      - ./cache:/app/cache:rw  # Add explicit read-write flag
      - ./models:/app/models:rw  # Add explicit read-write flag
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      ml-base:
        condition: service_started
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - app-network

  mongo: 
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DEBUG=1
      - PERSISTENCE=1
      - DATA_DIR=/var/lib/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LEGACY_DIRECTORIES=1
      - DISABLE_CORS_CHECKS=1
      - LOCALSTACK_VOLUME_DIR=/var/lib/localstack
      - FORCE_NONINTERACTIVE=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack/data:/var/lib/localstack/data"
      - "./localstack/init-s3.sh:/docker-entrypoint-initaws.d/init-s3.sh"
      - "./cache/s3:/var/lib/localstack/s3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network
  frontend:
    build:
      context: ./playground 
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8080
    networks:
      - app-network
    depends_on:
      - api
networks:
  app-network:
    driver: bridge

volumes: 
  mongodb_data:
  redis_data:
  localstack_data: